### ISSUE TITLE
Neispravna poveznica na sliku u README.md ?

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Real-time-clock-RTC-PCF85063A-breakout-hardware-design#1]
https://github.com/SolderedElectronics/Real-time-clock-RTC-PCF85063A-breakout-hardware-design/blob/d8029981341a43b5924bf5fe84544b531ad3bf25/README.md?plain=1#L5C45-L5C189

umjesto:

https://github.com/SolderedElectronics/Real-time-clock-RTC-PCF85063A-breakout-board-hardware-design/blob/main/OUTPUTS/V1.1.1/333051.jpg?raw=true

čini mi se da bi trebalo biti:

https://github.com/SolderedElectronics/Real-time-clock-RTC-PCF85063A-breakout-hardware-design/blob/main/OUTPUTS/V1.2.2/333051.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
